name: aqueduct
version: 4.0.0-b1
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
homepage: https://aqueduct.io
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: ^1.6.0
  analyzer: '>=0.39.4 <0.50.0'
  crypto: ^2.1.5
  logging: ^0.11.4
  isolate_executor: ^2.0.2+3
  meta: ^1.2.4
  open_api: ^2.0.1
  password_hash: ^2.0.0
  path: ^1.7.0
  postgres: ^2.2.0
  pub_cache: '>=0.2.0 <0.3.0'
  pub_semver: ^1.4.4
  safe_config: ^2.0.2
  yaml: ^2.2.1
  runtime: ^1.0.0-9

dev_dependencies:
  matcher: '>=0.12.3 <0.14.0'
  test: ^1.15.7
  http: '>=0.11.3+7 <0.13.0'
  command_line_agent: ^1.0.0-b2
  aqueduct_test:
    path: ../aqueduct_test

executables:
  aqueduct: aqueduct